app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime, timezone, time, timedelta,timezone
import pytz


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username=db.Column(db.String(255),unique=True,nullable=False)
    email = db.Column(db.String(255),unique = True,index = True)
    password_hash=db.Column(db.String(255))
    bio=db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    comment=db.relationship('Comment',backref='user',lazy='dynamic')
    blog=db.relationship('Blog',backref='user',lazy='dynamic')
    password_secure = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot access the password')

    @password.setter
    def password(self,password):
        self.password_hash=generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)


    def __repr__(self):
        return f"User('{self.username}','{self.email}','{self.blog}')"

class Comment(db.Model):
    __tablename__='comments'
    id=db.Column(db.Integer,primary_key=True)
    comment=db.Column(db.String)
    posted=db.Column(db.DateTime,default=datetime.utcnow)
    user_id=db.Column(db.Integer,db.ForeignKey("users.id"))
    blog_id=db.Column(db.Integer,db.ForeignKey('blog.id'))


    def __repr__(self):
        return f"Comment ('{self.comment}','{self.user}')"
        
    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,blog_id):
        comment=Comment.query.filter_by(blog_id=blog_id).all()
        return comment


class Blog(db.Model):
    __tablename__='blog'
    id=db.Column(db.Integer,primary_key=True)
    blog=db.Column(db.String())
    blog_category=db.Column(db.String(20))
    posted=db.Column(db.DateTime,default=datetime.utcnow)
    user_id=db.Column(db.Integer,db.ForeignKey('users.id'))

class Quote:
    def __init__(self, id, author, quote, permalink):
        self.id = id
        self.author = author
        self.quote = quote
        self.permalink = permalink

date_time=datetime.utcnow().replace(tzinfo=pytz.UTC)
time_zone=date_time.astimezone(pytz.timezone('Africa/Nairobi'))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required,length,DataRequired
from flask_wtf.file import FileField,file_allowed

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about yourself.',validators = [Required()])
    submit = SubmitField('Submit')

class UploadBlog(FlaskForm):
    blog=TextAreaField('Write Blog:',validators=[DataRequired()])
    submit=SubmitField('Post Blog')

class CommentsForm(FlaskForm):
    comment=TextAreaField('Type comment:', validators=[DataRequired()])
    submit=SubmitField('Post Comment')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
simple = SimpleMDE()
mail = Mail()

photos = UploadSet('photos',IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')


    # Will add the views and forms

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
import os
import functools
import secrets
from flask import render_template,redirect,url_for,abort,flash,request
from . import main
from flask_login import login_required,current_user
from ..models import User,Comment,Blog
from .. import db,photos
from .forms import UpdateProfile,UploadBlog,CommentsForm
from flask import current_app
from ..requests import get_quotes


@main.route('/')
def index():
    quotes = get_quotes()
    title = 'Blogs | Hub'
    page=request.args.get('page',1,type=int)
    all_blog=Blog.query.order_by(Blog.posted.desc()).paginate(page=page,per_page=10)
  
    return render_template('index.html',blogs=all_blog, title = title, quotes=quotes)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
   
    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/upload/blog',methods=['GET','POST'])
@login_required
def upload_blog():
    blog=UploadBlog()
    if current_user is None:
        abort(404)
    if blog.validate_on_submit():
        blog=Blog(blog=blog.blog.data,user=current_user)
        db.session.add(blog)
        db.session.commit()
        flash('Blog Uploaded')
        return redirect(url_for('main.index'))
    return render_template('profile/update_blog.html',blog=blog,title='Create Blog',legend='Create Blog')

@main.route('/<int:pname>/update',methods=['GET','POST'])
@login_required
def update(pname):
    blogs=UploadBlog()
    blog=Blog.query.get(pname)
    if blog.user != current_user:
        abort(403)
    if blogs.validate_on_submit():
        blog.blog_category=blogs.category.data
        blog.blog=blogs.blog.data
        db.session.commit()
        flash('Successfully Updated!')
        return redirect(url_for('main.profile',uname=blog.user.username))
    elif request.method=='GET':
        blogs.category.data=blog.blog_category
        blogs.blog.data=blog.blog

    return render_template('profile/update_blog.html',blog=blogs,legend="Update Blog")

@main.route('/<int:blog_id>/delete',methods=['POST'])
@login_required
def delete_blog(blog_id):
    blog=Blog.query.get(blog_id)
    if blog.user != current_user:
        abort(403)
    
    db.session.delete(blog)
    db.session.commit()

    return redirect(url_for('main.profile',uname=blog.user.username))


@main.route('/profile/user/<string:username>')
def posted(username):
    user=User.query.filter_by(username=username).first_or_404()
    image=url_for('static',filename='profile/'+ user.profile_pic_path)
    page=request.args.get('page',1,type=int)
    all_blog=Blog.query.filter_by(user=user)\
            .order_by(Blog.posted.desc())\
            .paginate(page=page,per_page=10)

    return render_template('posted_by.html',blogs=all_blog,title=user.username,user=user,image=image)

   

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title> Welcome to Blog App </title>
    {% endif %}
  </head>

  <body>
    <div>
      {%block styles %}
        {{super()}}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <!--Importing the simple mde css and js files  -->
        {{ simplemde.css}}
        {{ simplemde.js }}
      {% endblock %}

      {% block navbar %}
          {% include 'navbar.html' %}
      {% endblock %}

      {% block content%}
      {% endblock%}
    </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.ckeditor.com/4.6.2/basic/ckeditor.js"></script>
    <script type="text/javascript">CKEDITOR.replace('editor')</script>
  </body>
  
</html>

app/templates/blog.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block styles%}
    {{super()}}
        <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/index.css')}}">
{% endblock%}

{% block content%}
    <div class="row">
        <div class="col-md-2 col-lg-3 col-xs-1"></div>
        <div class="col-md-8 col-lg-6 col-xs-10 jumbotron">
            <div class="card mb-6 bg-dark text-white" style="text-align: center;">
                <div class="card-body">
                <h4 class="card-title" style="color:rgb(250, 157, 176)">Posted By: {{blog.user.username}}</h4>
                <p class="card-text">{{blog.blog}}</p>
                <p class="card-text" style="color:rgb(243, 180, 192)">Posted On: {{blog.posted.strftime('%Y-%m-%d')}}
                </div>
            </div>
           
            <div class="collapse" id="collapseExample">
                <div class="card card-body form-inline">
                    {{wtf.quick_form(comment)}}
                </div>
            </div>
            <hr>
            <div class=" card comments">
                <h4 class="card-header">View all post comments</h4>
                <ul>
                    {% for comment in comments%}
                    <li style="list-style-type: none;">
                        <div class="col-md-2 col-lg-2 col-sm-2 col-xs-2">
                            {% if comment.user.profile_pic_path %}
                            <img src="{{url_for('static',filename=comment.user.profile_pic_path)}}" class="img-circle img-responsive" style="width: 50px; height: 50px;">
                            {%else%}
                            <img src="{{url_for('static', filename='profile/profile.png')}}" class="card-img rounded-circle" alt="" style="width: 25px; height: 25px;">
                            {% endif %}
                        </div>
                        <div class="col-md-10 col-lg-10 col-sm-10 col-xs-10">
                                <span class="header">{{comment.user.username}}</span> <br>
                                <span class="rounded">{{comment.comment}} </span><hr>                          
                        </div>
                    </li>
                    <br>
                    {% endfor%}
                </ul>
            </div>
        </div>
        <div class="col-md-2 col-lg-3 col-xs-1"></div>
    </div>
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOPS! PAGE NOT FOUND</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}

{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    {% endblock%}
{% block content%}
    <div class="container" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
        <div class="jumbotron text-center">
            <h1 class="lead"><strong>MyBlogApp</strong></h1>
            <h4>'There is no better way to express your ideas and opinions than with a personal blog.'</h4>
        </div>
    </div>
    <div class="row" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
        <div class="col-md-2 col-lg-2 col-xs-1"></div>
        <div class="col-md-8 col-lg-8 col-xs-10 ">
            <div class="jumbotron">
                <h4 style="color: darkblue;"><strong>Quote</strong></h4>
                <p style="color: darkblue;" >{{quotes.quote}}</p>
                <p style="color: brown;">By:{{quotes.author}}</p>
            </div>
            <h1 style="text-align: center;">Blogs</h1>
            <ul class="list-index ">
                {% for blog in blogs.items%}
                <li class="jumbotron " style="padding-left:40px ; list-style-type: none;">                 
                    <div class="card mb-6 bg-dark text-white">
                        <div class="card-body">
                            <p class="card-text"><strong>{{blog.blog   }}</strong></p>
                            <p class="card-text" style="color:brown">Posted On: {{blog.posted.strftime('%Y-%m-%d')}}</p>
                        
                            <h5>Leave a Comment</h5>
                            <input type="text" placeholder="Enter your name" id="name"><br>
                            <br>
                            <input type="text" aria-rowcount="5" placeholder=" Enter comment" id="comment"><br>
                            <br>
                            <button onclick="add()">Submit</button>
                            <button onclick="location.reload()">Clear</button>
                            <ul class="list"></ul>
                        </div>
                    </div>              
                </li>
                <br>
                {%endfor%}
            </ul>
        </div>
        
        <div class="col-md-2 col-lg-2 col-xs-1"></div>
    </div>
    <script type="text/javascript">
        let add = () => {
        let name = document.querySelector('.container #name'); 
        let comment = document.querySelector('.container #comment'); 
        
        if (name.value !== "" && comment.value != "") { 
        
        let list = document.querySelector('.list'); 
        let time = new Date();
        let h = time.getHours(); 
        let m = time.getMinutes(); 
        let s = time.getSeconds(); 
        let now = h + " : " + m + " : " + s;
        let list_item = document.createElement ("l1"); 
        
        list_item.innerHTML = `
        <span>
        <p>${name.value} ${now}</p> 
        </span>
        <p>${comment.value}</p>
        `;
        list.append(list_item); 
        }
        
        if (name.value == "" || comment.value == "") {
        let list = document.querySelector('.list'); 
        let list_item = document.createElement ("l2"); 
        var warn = 'Please enter name & comment!';  
        list_item.innerHTML = `
        <span>
        <p>${warn}</p> 
        </span>
        `;
        list.append(list_item); 
        }
        name.value=comment.value = "";
        }
        
      </script>
   
{% endblock %}

app/templates/macros.html
<!-- Displaying reviews macro -->
{% macro displayReviews(review_list) %}

    {% for review in review_list %}

    <div class="row">

      <div class="col-xs-2 col-sm-2 col-md-4 col-lg-4">
        <h4>Author</h4>
        <p>{{review.user.username}}</p>
      </div>
      <div class="col-xs-10 col-sm-10 col-md-8 col-lg-8">
        <h2> <a href="{{url_for('main.single_review',id=review.id)}}">{{review.blog_title}}</a> </h2>
      </div>
    </div>

    {% endfor %}
{% endmacro %}

app/templates/main.html
<main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-4">
        <div class="content-section">
          <h3>Our Sidebar</h3>
          <p class='text-muted'>You can put any information here you'd like.
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Latest Posts</li>
              <li class="list-group-item list-group-item-light">Announcements</li>
              <li class="list-group-item list-group-item-light">Calendars</li>
              <li class="list-group-item list-group-item-light">etc</li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </main>

app/templates/navbar.html
<nav class="navbar navbar-default">
    <div role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">MyBlogApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{url_for('main.index')}}">Home</a></li>
                    <li><a href="{{url_for('main.upload_blog')}}">Post Blog</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                        {% if current_user.is_authenticated%}
                        <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                        {% else %}
                        <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                        {%endif%}
                </ul>
            </div>
        </div>
    </div>    
</nav>  

app/templates/new_blog.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

app/templates/new_pitch.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

app/templates/new_review.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="col-md-8">

           
        </div>

        <div class="col-md-4">

            {{ wtf.quick_form(review_form) }}
        </div>
        
        <div class="col-md-4">
            {{ wtf.quick_form(review_form) }}
            {{simplemde.load}}
        </div>
    </div>

{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block styles%}
    {{super()}}
        <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/index.css')}}">
{% endblock%}

{% block content%}
    <div class="row">
        <div class="col-md-2 col-lg-3 col-xs-1"></div>
        <div class="col-md-8 col-lg-6 col-xs-10 jumbotron">
            <div class="card mb-6 bg-dark text-white" style="text-align: center;">
                <div class="card-body">
                <h4 class="card-title" style="color:rgb(250, 157, 176)">Pitch Category: {{pitch.pitch_category}}<span></span>Posted By: {{pitch.user.username}}</h4>
                <p class="card-text">{{pitch.pitch}}</p>
                <p class="card-text" style="color:rgb(243, 180, 192)">Posted On: {{pitch.posted.strftime('%Y-%m-%d')}}<span></span>Likes: {{pitch.upvotes}}~<span></span>Dislikes: {{pitch.downvotes}}</p>
                </div>
            </div>
           
            <div class="collapse" id="collapseExample">
                <div class="card card-body form-inline">
                    {{wtf.quick_form(comment)}}
                </div>
            </div>
            <hr>
            <div class=" card comments">
                <h4 class="card-header">View all post comments</h4>
                <ul>
                    {% for comment in comments%}
                    <li style="list-style-type: none;">
                        <div class="col-md-2 col-lg-2 col-sm-2 col-xs-2">
                            {% if comment.user.profile_pic_path %}
                            <img src="{{url_for('static',filename=comment.user.profile_pic_path)}}" class="img-circle img-responsive" style="width: 50px; height: 50px;">
                            {%else%}
                            <img src="{{url_for('static', filename='profile/profile.png')}}" class="card-img rounded-circle" alt="" style="width: 25px; height: 25px;">
                            {% endif %}
                        </div>
                        <div class="col-md-10 col-lg-10 col-sm-10 col-xs-10">
                                <span class="header">{{comment.user.username}}</span> <br>
                                <span class="rounded">{{comment.comment}} </span><hr>                          
                        </div>
                    </li>
                    <br>
                    {% endfor%}
                </ul>
            </div>
        </div>
        <div class="col-md-2 col-lg-3 col-xs-1"></div>
    </div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/profile.css')}}">
{% endblock%}

{% block content %}
<div class="container">
  <div class="row">
  <!-- displaying  Username-->
    <div class="col-md-4">
      <h3> {{user.username| capitalize}} </h3>

      <!--Displaying user bio-->
      {% if user.bio %}
        <p> {{user.bio}}</p>
      {%else%}
        <p> {{user.username| capitalize}} has no bio </p>
      {% endif %}
    </div>

    <!--Display profile photo-->
    <div class="col-md-4">

      {% if user.profile_pic_path %}
        <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
        {%else%}
        <p>No profile picture</p>
      {% endif %}

      {% if user == current_user %}
        <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

          <input type="file"  name="photo" class="form-control" required><br>
          <br>
          <input type="submit">
        </form>
      {% endif %}
    </div>
  </div>

  <div class="row">
    <div class="col-md-2 col-lg-2 col-sm-0"></div>
    <div class="col-md-8 col-sm-12 col-lg-8">
      <ul class="list-group">
        {% for blog in blogs%}
        <li class="list-group-item">
            
            <div class="card w-75">
              <div class="card-body">
                <h4 class="card-title"><span class="badge badge-default">Date Posted: <span class="badge badge-light">{{blog.posted.strftime('%Y-%m-%d')}}</span></span></span></h4>
                <p class="card-text">{{blog.blog}}</p>
                {% if blog.user==current_user%}
                <div>
                  <a href="{{url_for('main.update',pname=blog.id)}}" class="btn btn-primary btn-sm">Update</a>
                  <button type="button" class="btn btn-danger btn-sm m-2" data-toggle="modal" data-target="#deleteModal" href="{{url_for('main.delete_blog',blog_id=blog.id)}}">Delete</button>
                </div>
                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete this blog</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-footer ">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <form action="{{url_for('main.delete_blog',blog_id=blog.id)}}" method="POST">
                            <input class="btn btn-danger" type="submit" value="Delete">
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
                {%endif%}                          
              </div>
            </div>
        </li>
        {% endfor%}
      </ul>
    </div>
    <div class="col-md-2 col-lg-2 col-sm-0"></div>
</div>

</div>
{% endblock content %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/profile/update_blog.html
{% import 'bootstrap/wtf.html' as wtf %}
{% extends 'base.html'%}
{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/index.css')}}">
{% endblock%}
{% block content%}
<div class="container">
    <div class="row">
        <div class="col-md-2 col-lg-3"></div>
        <div class="col-md-8 col-sm-12 col-lg-6">
            <legend class="border-bottom mb-4">{{legend}}</legend>
        <!-- Flash message -->
        {% for message in get_flashed_messages()%}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor%}
            {{wtf.quick_form(blog)}}
        </div>

        <div class="col-md-2 col-lg-3"></div>  
    </div>
</div>

{% endblock%}

app/templates/profile/update_pitch.html
{% import 'bootstrap/wtf.html' as wtf %}
{% extends 'base.html'%}
{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/index.css')}}">
{% endblock%}
{% block content%}
<div class="container">
    <div class="row">
        <div class="col-md-2 col-lg-3"></div>
        <div class="col-md-8 col-sm-12 col-lg-6">
            <legend class="border-bottom mb-4">{{legend}}</legend>
        <!-- Flash message -->
        {% for message in get_flashed_messages()%}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor%}
            {{wtf.quick_form(pitch)}}
        </div>

        <div class="col-md-2 col-lg-3"></div>  
    </div>
</div>

{% endblock%}